name: PR Tests

on: [ pull_request ]

jobs:
  check_projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install pyyaml
      - name: Run PR checker
        run: |
          python .github/workflows/pr_checker.py